services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: gymemo
    networks:
      - gymemo_net

  backend:
    image: pasitkku/gymemo-backend:latest
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://mongo:27017/gymemo
      JWT_SECRET: 6c06c7c527490ad80653edeb673cfe8e
    depends_on:
      - mongo
    networks:
      - gymemo_net

  frontend:
    image: pasitkku/gymemo-frontend:v9
    restart: unless-stopped
    ports:
      - "3002:3000"
    depends_on:
      - backend
    networks:
      - gymemo_net

volumes:
  mongo_data:

networks:
  gymemo_net:
