version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: gymemo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: gymemo

volumes:
  mongo-data:
